name: Kubernetes preview environments

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      # - closed - destroy preview environment

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: demo-preview-environments 
  GKE_ZONE: europe-north1-a
  PR_NUMBER: pr-${{ github.event.number }}
  INGRESS_IP: ${{ secrets.INGRESS_IP }}

jobs:
  deploy-preview-environment:
    name: Deploy to Preview
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/793381027767/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'sa-deploy@starry-minutia-376412.iam.gserviceaccount.com'

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Docker login
    - uses: 'docker/login-action@v1'
      with:
        registry: 'eu.gcr.io'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    # Run "docker login" directly to Container Registry.
    - run: |-
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io

    # Install Garden CLI tool
    - name: Set up Garden
      run: |-
        curl -sL https://get.garden.io/install.sh | bash
        export PATH=$PATH:$HOME/.garden/bin
        chmod u+x $HOME/.garden
        echo "PATH=$HOME/.garden/bin:$PATH" >> $GITHUB_ENV

    # Deploy the preview environment to the GKE cluster
    - name: Deploy
      run: |-
        cd ./demo-project-start
        garden --version
        garden --env=preview plugins kubernetes cluster-init
        garden deploy
        garden get status

